{% set name = "openinference-instrumentation-mistralai" %}
{% set version = "0.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openinference_instrumentation_mistralai-{{ version }}.tar.gz
  sha256: 1d03096165ee67c4e89861c82082578e38704845e3fa18e56fb3655a389cbed6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<3.13
    - hatchling
    - pip
  run:
    - python >=3.8,<3.13
    - opentelemetry-api
    - opentelemetry-instrumentation
    - opentelemetry-semantic-conventions
    - openinference-instrumentation >=0.1.12
    - openinference-semantic-conventions >=0.1.9
    - wrapt

test:
  imports:
    - openinference.instrumentation.mistralai
  commands:
    - pip check
  requires:
    - pip

about:
  summary: OpenInference Mistral AI Instrumentation
  home: https://github.com/Arize-ai/openinference
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mikeldking
    - anticorrelator
    - RogerHYang
    - michaelschiff
    - axiomofjoy
